### ISSUE TITLE
The Person#question_sets method returns an empty array.

### ISSUE THREAD

**Issue by DelmerGA** [BlockScore/blockscore-ruby#22] opened 2015-08-21 08:11 UTC
One would expect that `Person#question_sets` would return the array of `id`'s for the `question_sets` associated to a `Person`. However, the method returns an empty array.

**Comment by backus** [comment] 2015-08-21 08:14
I agree it should be fixed.  I'm not sure if the expectation should be that we get an array of `id`s.  Instead, I would thing it would be an array lazily requested `QuestionSet` objects.

**Comment by connorjacobsen** [comment] 2015-08-22 09:56
Dammit. @DelmerGA do you still have the offending code sample? I thought that was something I fixed previously.

I also agree with @backus that it should return objects rather than `id`s, both for consistency across the library, and because users will expect objects rather than strings.

**Comment by connorjacobsen** [comment] 2015-08-22 10:03
It appears the issue is with how `Person` objects are initialized. After the `super` call, a new `QuestionSet` collection is instantiated, and given the correct `Person` `id`, but existing `QuestionSets` are not loaded, even though we should already have their `id`s from when the `Person` was fetched.

The question, @backus, is what assumptions do we / can we make about the `Person` object? Should we assume that a given `Person` may have been updated by some other object somewhere else in a user's program since the `QuestionSets` were loaded? Or is that an unlikely scenario?

**Comment by backus** [comment] 2015-08-22 10:06
How would they without going through the client?

**Comment by connorjacobsen** [comment] 2015-08-22 10:10
I meant if they somehow had two separate objects in their program that both retrieved the same `Person`, and then they did some operations on one of the objects (i.e., created a new question set), and then called the `question_sets` method on the other object.

**Comment by backus** [comment] 2015-08-22 10:21
That would be fine.  If they had two blockscore instances, fetched a person with the first, and created a question set for that person with the second, then the expected state for the first would still be that nothing about it changes.  That isn't the recommended use case and, if someone did want that for some reason, they could call the `#refresh` method.

**Comment by connorjacobsen** [comment] 2015-08-22 10:48
:+1: Then I think the fix would be as simple as updating the `QuestionSet` `Collection` upon `Person` instantiation and / or changing the `question_sets` reader into a proper method that handles the lazy loading.

**Comment by DelmerGA** [comment] 2015-08-22 10:49
I made the suggestion for `Person#question_sets` returning an array of id's because it currently returns something like that. Assuming we have  some `Person` that already has a few `QuestionSet`s or not we see the following:

```ruby
person = BlockScore::Person.retrieve("some_id")
#=> #<BlockScore::Person: ...>
person.question_sets
#=> []  
person.question_sets.create
#=>#<BlockScore::QuestionSet: ... >
person.question_sets.create
#=>#<BlockScore::QuestionSet: ... >
person.question_sets
#=>["55d84ea83735320003000194",  "55d8502d336335000300021e"]
person.question_sets[0]
#=> "55d84ea83735320003000194"
```

If someone has just been creating `question_sets` and accessing the recently created id's they might not have noticed the issue that pre-existing `QuestionSet`s were not being returned for a `Person`. Changing it to return objects might even break their code in this rare situation, but I think it's worth fixing and having the `QuestionSet` objects lazily loaded.

**Comment by DelmerGA** [comment] 2015-08-23 01:25
All tests are currently passing for the question sets. Let's make sure to add a test case since we're not currently catching it.

**Comment by backus** [comment] 2015-08-23 01:26
I'll open a WIP PR with a failing test

**Closed** 2015-09-15 01:15 UTC
Labels: bug
